package admin

const pageTemplates = `
{{define "head"}}<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>{{.Title}} · Image Gateway</title><style>
body{font:15px system-ui;background:#111827;color:#e5e7eb;margin:0}main{max-width:1100px;margin:auto;padding:24px}nav{display:flex;gap:18px;padding:16px;background:#1f2937}a{color:#93c5fd}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #374151;text-align:left;max-width:330px;overflow-wrap:anywhere}input,button{padding:9px;background:#111827;color:#fff;border:1px solid #4b5563;border-radius:5px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#030712;padding:14px;border-radius:6px}img{max-width:160px;max-height:120px}.bad{color:#fca5a5}.ok{color:#86efac}.pager{display:flex;gap:16px;margin:20px 0}
</style></head><body>{{end}}
{{define "nav"}}<nav><a href="/">概览</a><a href="/requests">请求</a><a href="/images">图片</a><a href="/settings">设置</a><form method="post" action="/logout"><input type="hidden" name="csrf" value="{{.CSRF}}"><button>退出</button></form></nav>{{end}}
{{define "login"}}{{template "head" .}}<main><h1>Image Gateway</h1><p class="bad">{{.Error}}</p><form method="post"><p><input name="username" autocomplete="username" placeholder="管理员"></p><p><input type="password" name="password" autocomplete="current-password" placeholder="密码"></p><button>登录</button></form></main></body></html>{{end}}
{{define "dashboard"}}{{template "head" .}}{{template "nav" .}}<main><h1>概览</h1><p>{{.Error}}</p><p>可用磁盘空间：{{.Free}} bytes</p></main></body></html>{{end}}
{{define "requests"}}{{template "head" .}}{{template "nav" .}}<main><h1>请求记录</h1><table><tr><th>时间</th><th>模型</th><th>提示词</th><th>状态</th><th>耗时</th></tr>{{range .Requests}}<tr><td><a href="/requests/{{.ID}}">{{.CreatedAt}}</a></td><td>{{.Model}}</td><td>{{.Prompt}}</td><td>{{.Status}}</td><td>{{.DurationMS}} ms</td></tr>{{end}}</table><div class="pager">{{if .HasPrevious}}<a href="?page={{.PreviousPage}}">上一页</a>{{end}}<span>第 {{.Page}} 页</span>{{if .HasNext}}<a href="?page={{.NextPage}}">下一页</a>{{end}}</div></main></body></html>{{end}}
{{define "request"}}{{template "head" .}}{{template "nav" .}}<main><h1>请求 {{.Request.ID}}</h1><p>{{.Request.Model}} · {{.Request.Status}}</p><h2>请求体</h2><pre>{{.Request.RequestBody}}</pre><h2>原始响应</h2><pre>{{.Request.RawResponse}}</pre><h2>改写响应</h2><pre>{{.Request.RewrittenResponse}}</pre><form method="post" action="/requests/{{.Request.ID}}/delete"><input type="hidden" name="csrf" value="{{.CSRF}}"><button>删除请求及其图片</button></form></main></body></html>{{end}}
{{define "images"}}{{template "head" .}}{{template "nav" .}}<main><h1>图库</h1><table><tr><th>预览</th><th>来源</th><th>状态</th><th>操作</th></tr>{{range .Images}}<tr><td>{{if eq .Status "READY"}}<img loading="lazy" src="{{.PublicURL}}">{{end}}</td><td>{{.SourceURL}}</td><td>{{.Status}}<br><span class="bad">{{.Error}}</span></td><td>{{if eq .Status "FAILED"}}<form method="post" action="/images/{{.ID}}/retry"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>重试</button></form>{{end}}<form method="post" action="/images/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>删除</button></form></td></tr>{{end}}</table><div class="pager">{{if .HasPrevious}}<a href="?page={{.PreviousPage}}">上一页</a>{{end}}<span>第 {{.Page}} 页</span>{{if .HasNext}}<a href="?page={{.NextPage}}">下一页</a>{{end}}</div></main></body></html>{{end}}
{{define "settings"}}{{template "head" .}}{{template "nav" .}}<main><h1>运行设置</h1><p>配置版本 {{.Runtime.Version}}</p><form method="post"><input type="hidden" name="csrf" value="{{.CSRF}}"><p>下载总尝试次数 <input name="download_attempts" value="{{.Runtime.DownloadAttempts}}"></p><p>退避基数 <input name="retry_base_delay" value="{{.Runtime.RetryBaseDelay}}"></p><p>最大重定向 <input name="max_redirects" value="{{.Runtime.MaxRedirects}}"></p><button>原子保存</button></form><p>配置变更以单个事务保存，并立即对新下载任务生效；进行中的任务保持原策略。</p></main></body></html>{{end}}`
